{"uuid": "99337de8-b518-46ae-833d-ac9b854a5726", "children": ["b93bdc78-c8d7-494a-8eff-215a8300291c"], "befores": [{"name": "get_key", "status": "failed", "statusDetails": {"message": "AssertionError: assert 500 == 200\n  +500\n  -200\n", "trace": "  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\python_Code\\pythonProject\\pythonclasses\\autoclass\\day10\\apiautotest\\conftest.py\", line 20, in get_key\n    return test_user_api.test_user_login()\n  File \"D:\\python_Code\\pythonProject\\pythonclasses\\autoclass\\day10\\apiautotest\\testcase\\test_user_api.py\", line 27, in test_user_login\n    assert res.status_code == 200\n"}, "start": 1689263251678, "stop": 1689263251815}], "start": 1689263251678, "stop": 1689263251832}